version: '3'
services:
    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    pgdata: {}
